update the entry points for config_manager
ansible-network/config_manager pull request #1
Opened 2018-09-04 14:54 UTC by privateip

This change will update the entry points to drop the _config from the
task entry points.  It also adds the main task to map functions to tasks
for direct role execution.

2018-09-04 20:45 UTC, gundalow requested changes
Could you please add the `ansible_min_version` from `network-engine` in here?

2018-09-04 20:45 UTC, gundalow commented on includes/init.yaml
> +    ansible_network_config_manager_version: "devel"
What would this be needed for?

2018-09-05 04:20 UTC, trishnaguha commented on includes/init.yaml
> +  when: ansible_network_os is undefined
this is should be `when: ansible_network_provider is undefined`

2018-09-05 20:57 UTC, privateip commented on includes/init.yaml
> +    ansible_network_config_manager_version: "devel"
support

2018-09-05 20:57 UTC, privateip commented on includes/init.yaml
> +  when: ansible_network_os is undefined
good catch

2018-09-06 04:59 UTC, trishnaguha approved these changes

2018-09-10 13:51 UTC, gundalow approved these changes

2018-09-10 13:51 UTC, merged